// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApiKeyListResponse struct {
	Code      int32        `json:"code"`
	Msg       string       `json:"msg"`
	Timestamp int64        `json:"timestamp"`
	Data      []ShowApiKey `json:"data"`
}

type ChatCompletionChoice struct {
	Index        int             `json:"index"`
	Message      OpenChatMessage `json:"message"`
	FinishReason string          `json:"finishReason"`
}

type ChatCompletionRequest struct {
	Model           string            `json:"model,optional"`           // 模型标识（空则用系统默认）
	Messages        []OpenChatMessage `json:"messages"`                 // 对话消息列表
	KnowledgeBaseID int64             `json:"knowledgeBaseId,optional"` // 关联知识库 ID（启用 RAG）
	MaxTokens       int               `json:"maxTokens,optional"`       // 最大生成 token 数
	Temperature     float64           `json:"temperature,optional"`     // 温度参数 [0,2]
	Stream          bool              `json:"stream,optional"`          // 是否流式返回（true 时走 SSE）
}

type ChatCompletionResponse struct {
	ID      string                 `json:"id"`
	Object  string                 `json:"object"`
	Model   string                 `json:"model"`
	Choices []ChatCompletionChoice `json:"choices"`
	Usage   ChatCompletionUsage    `json:"usage"`
	Sources []string               `json:"sources,omitempty"` // RAG 命中的知识来源
}

type ChatCompletionUsage struct {
	PromptTokens     int `json:"promptTokens"`
	CompletionTokens int `json:"completionTokens"`
	TotalTokens      int `json:"totalTokens"`
}

type CloseConversationRequest struct {
	ID int64 `path:"id"`
}

type CommResponse struct {
	Code      int32  `json:"code,example=0"`                  // 业务状态码，0 表示成功
	Msg       string `json:"msg,example=OK"`                  // 响应消息
	Timestamp int64  `json:"timestamp,example=1715300000000"` // 响应时间戳（Unix 毫秒）
}

type ConversationDetailResponse struct {
	Code      int32            `json:"code"`
	Msg       string           `json:"msg"`
	Timestamp int64            `json:"timestamp"`
	Data      ShowConversation `json:"data"`
}

type ConversationListData struct {
	Total int64              `json:"total"`
	List  []ShowConversation `json:"list"`
}

type ConversationListResponse struct {
	Code      int32                `json:"code"`
	Msg       string               `json:"msg"`
	Timestamp int64                `json:"timestamp"`
	Data      ConversationListData `json:"data"`
}

type CreateApiKeyData struct {
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	Key       string   `json:"key"`       // 原始 API Key（仅创建时返回）
	KeyPrefix string   `json:"keyPrefix"` // 密钥前缀
	Scopes    []string `json:"scopes"`
}

type CreateApiKeyRequest struct {
	Name   string   `json:"name"`            // 密钥名称
	Scopes []string `json:"scopes,optional"` // 权限范围（默认 ["chat"]）
}

type CreateApiKeyResponse struct {
	Code      int32            `json:"code"`
	Msg       string           `json:"msg"`
	Timestamp int64            `json:"timestamp"`
	Data      CreateApiKeyData `json:"data"`
}

type CreateConversationRequest struct {
	KnowledgeBaseID int64  `json:"knowledgeBaseId,optional"` // 关联知识库 ID
	Title           string `json:"title,optional"`           // 会话标题
	Model           string `json:"model,optional"`           // 指定聊天模型（空则用默认模型）
	Channel         string `json:"channel,default=web"`      // 接入渠道: web / api / webhook
}

type CreateKnowledgeBaseRequest struct {
	Name        string `json:"name"`                                          // 知识库名称
	Description string `json:"description,optional"`                          // 知识库描述
	Model       string `json:"model,optional,default=text-embedding-3-small"` // Embedding 模型
}

type CreateWebhookRequest struct {
	Name        string   `json:"name"`                        // Webhook 名称
	URL         string   `json:"url"`                         // 回调 URL
	Secret      string   `json:"secret,optional"`             // 签名密钥（可选）
	Events      []string `json:"events,optional"`             // 订阅事件类型列表
	ChannelType string   `json:"channelType,default=webhook"` // 渠道类型
	RetryCount  int      `json:"retryCount,default=3"`        // 重试次数
	TimeoutMs   int      `json:"timeoutMs,default=5000"`      // 超时毫秒
}

type DeleteDocumentRequest struct {
	KnowledgeBaseID int64 `path:"kbId"`
	ID              int64 `path:"id"`
}

type DeleteKnowledgeBaseRequest struct {
	ID int64 `path:"id"` // 知识库 ID
}

type DeleteWebhookRequest struct {
	ID int64 `path:"id"`
}

type DependencyStatus struct {
	Name  string `json:"name,example=mysql"`      // 依赖名称，如 mysql、redis
	Ready bool   `json:"ready,example=true"`      // 是否就绪
	Error string `json:"error,optional,example="` // 错误信息，就绪时为空
}

type DocumentDetailResponse struct {
	Code      int32        `json:"code"`
	Msg       string       `json:"msg"`
	Timestamp int64        `json:"timestamp"`
	Data      ShowDocument `json:"data"`
}

type DocumentListData struct {
	Total int64          `json:"total"`
	List  []ShowDocument `json:"list"`
}

type DocumentListResponse struct {
	Code      int32            `json:"code"`
	Msg       string           `json:"msg"`
	Timestamp int64            `json:"timestamp"`
	Data      DocumentListData `json:"data"`
}

type EscalateConversationRequest struct {
	ID     int64  `path:"id"`
	Reason string `json:"reason,optional"` // 转接原因（可选）
}

type GetConversationRequest struct {
	ID int64 `path:"id"`
}

type GetKnowledgeBaseRequest struct {
	ID int64 `path:"id"` // 知识库 ID
}

type GetWebhookRequest struct {
	ID int64 `path:"id"`
}

type HealthResponse struct {
	Status string `json:"status,example=UP"` // 服务健康状态：UP / DOWN
}

type KnowledgeBaseDetailResponse struct {
	Code      int32             `json:"code"`
	Msg       string            `json:"msg"`
	Timestamp int64             `json:"timestamp"`
	Data      ShowKnowledgeBase `json:"data"`
}

type KnowledgeBaseListData struct {
	Total int64               `json:"total"` // 总数
	List  []ShowKnowledgeBase `json:"list"`  // 列表
}

type KnowledgeBaseListResponse struct {
	Code      int32                 `json:"code"`
	Msg       string                `json:"msg"`
	Timestamp int64                 `json:"timestamp"`
	Data      KnowledgeBaseListData `json:"data"`
}

type ListConversationRequest struct {
	Page     int    `form:"page,range=[1:]"`
	PageSize int    `form:"pageSize,range=[1:50]"`
	Status   string `form:"status,optional"`
}

type ListDocumentRequest struct {
	KnowledgeBaseID int64  `path:"kbId"`
	Page            int    `form:"page,range=[1:]"`
	PageSize        int    `form:"pageSize,range=[1:50]"`
	Status          string `form:"status,optional"`
}

type ListKnowledgeBaseRequest struct {
	Page     int    `form:"page,range=[1:]"`       // 页码
	PageSize int    `form:"pageSize,range=[1:50]"` // 每页条数
	Name     string `form:"name,optional"`         // 按名称模糊搜索
}

type ListMessageRequest struct {
	ConversationID int64 `path:"convId"`
	Page           int   `form:"page,range=[1:]"`
	PageSize       int   `form:"pageSize,range=[1:100]"`
}

type LoginData struct {
	Token    string   `json:"token,example=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."` // JWT 访问令牌
	ExpireAt int64    `json:"expireAt,example=1715386400000"`                        // 令牌过期时间（Unix 毫秒）
	User     ShowUser `json:"user"`                                                  // 当前登录用户信息
}

type LoginRequest struct {
	Email    string `json:"email,example=user@example.com"` // 登录邮箱
	Password string `json:"password,example=P@ssw0rd123"`   // 登录密码
}

type LoginResponse struct {
	Code      int32     `json:"code,example=0"`                  // 业务状态码，0 表示成功
	Msg       string    `json:"msg,example=OK"`                  // 响应消息
	Timestamp int64     `json:"timestamp,example=1715300000000"` // 响应时间戳（Unix 毫秒）
	Data      LoginData `json:"data"`                            // 登录数据
}

type MessageListData struct {
	Total int64         `json:"total"`
	List  []ShowMessage `json:"list"`
}

type MessageListResponse struct {
	Code      int32           `json:"code"`
	Msg       string          `json:"msg"`
	Timestamp int64           `json:"timestamp"`
	Data      MessageListData `json:"data"`
}

type ModelListData struct {
	ChatModels      []ShowModel `json:"chatModels"`      // 可用聊天模型
	EmbeddingModels []ShowModel `json:"embeddingModels"` // 可用 Embedding 模型
}

type ModelListResponse struct {
	Code      int32         `json:"code"`
	Msg       string        `json:"msg"`
	Timestamp int64         `json:"timestamp"`
	Data      ModelListData `json:"data"`
}

type OpenChatMessage struct {
	Role    string `json:"role"`    // 角色: system / user / assistant
	Content string `json:"content"` // 消息内容
}

type PingResponse struct {
	Message   string `json:"message,example=pong"`                             // 固定返回 "pong"
	TraceId   string `json:"traceId,example=4bf92f3577b34da6a3ce929d0e0e4736"` // 链路追踪 ID
	RequestId string `json:"requestId,example=req-a1b2c3d4"`                   // 请求唯一标识
}

type ReadyResponse struct {
	Status       string             `json:"status,example=READY"` // 整体就绪状态：READY / NOT_READY
	Dependencies []DependencyStatus `json:"dependencies"`         // 各依赖组件状态列表
}

type RegisterRequest struct {
	NickName string `json:"nick_name,example=张三"`           // 用户昵称
	Email    string `json:"email,example=user@example.com"` // 注册邮箱
	Password string `json:"password,example=P@ssw0rd123"`   // 注册密码
}

type RevokeApiKeyRequest struct {
	ID int64 `path:"id"`
}

type SendMessageRequest struct {
	ConversationID int64  `path:"convId"`                   // 会话 ID
	Content        string `json:"content"`                  // 消息内容
	ContentType    string `json:"contentType,default=text"` // 内容类型
}

type SendMessageResponse struct {
	Code      int32       `json:"code"`
	Msg       string      `json:"msg"`
	Timestamp int64       `json:"timestamp"`
	Data      ShowMessage `json:"data"`
}

type ShowApiKey struct {
	ID        int64    `json:"id"`
	Name      string   `json:"name"`
	KeyPrefix string   `json:"keyPrefix"`
	Scopes    []string `json:"scopes"`
	Status    string   `json:"status"`
	LastUsed  int64    `json:"lastUsed,omitempty"`
	ExpiresAt int64    `json:"expiresAt,omitempty"`
	CreatedAt int64    `json:"createdAt"`
}

type ShowConversation struct {
	ID              int64  `json:"id"`
	UUID            string `json:"uuid"`
	KnowledgeBaseID int64  `json:"knowledgeBaseId,omitempty"`
	Title           string `json:"title"`
	Model           string `json:"model,omitempty"`
	Status          string `json:"status"`
	Channel         string `json:"channel"`
	MessageCount    int    `json:"messageCount"`
	CreatedAt       int64  `json:"createdAt"`
	UpdatedAt       int64  `json:"updatedAt"`
}

type ShowDocument struct {
	ID          int64  `json:"id"`
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
	FileSize    int64  `json:"fileSize"`
	ChunkCount  int    `json:"chunkCount"`
	Status      string `json:"status"`
	ErrorMsg    string `json:"errorMsg,omitempty"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type ShowKnowledgeBase struct {
	ID          int64  `json:"id"`          // 知识库 ID
	UUID        string `json:"uuid"`        // 唯一标识
	Name        string `json:"name"`        // 知识库名称
	Description string `json:"description"` // 描述
	Model       string `json:"model"`       // Embedding 模型
	Dimension   int    `json:"dimension"`   // 向量维度
	Status      string `json:"status"`      // 状态
	DocCount    int    `json:"docCount"`    // 文档数
	ChunkCount  int    `json:"chunkCount"`  // 切块数
	CreatedAt   int64  `json:"createdAt"`   // 创建时间
	UpdatedAt   int64  `json:"updatedAt"`   // 更新时间
}

type ShowMessage struct {
	ID          int64    `json:"id"`
	UUID        string   `json:"uuid"`
	Role        string   `json:"role"`
	Content     string   `json:"content"`
	ContentType string   `json:"contentType"`
	TokenCount  int      `json:"tokenCount,omitempty"`
	Model       string   `json:"model,omitempty"`
	LatencyMs   int      `json:"latencyMs,omitempty"`
	Sources     []string `json:"sources,omitempty"`
	CreatedAt   int64    `json:"createdAt"`
}

type ShowModel struct {
	ID        string `json:"id"`                  // 模型标识（如 gpt-4o）
	Name      string `json:"name"`                // 展示名称
	Type      string `json:"type"`                // 类型: chat / embedding
	Provider  string `json:"provider,omitempty"`  // 供应商
	MaxTokens int    `json:"maxTokens,omitempty"` // 最大 context 窗口
	IsDefault bool   `json:"isDefault"`           // 是否为默认模型
}

type ShowUser struct {
	ID        int64  `json:"id,example=1"`                                      // 用户 ID
	UUID      string `json:"uuid,example=550e8400-e29b-41d4-a716-446655440000"` // 用户唯一标识
	TenantID  int64  `json:"tenantId,example=100"`                              // 所属租户 ID
	Email     string `json:"email,example=user@example.com"`                    // 邮箱
	NickName  string `json:"nickName,example=张三"`                               // 昵称
	Role      string `json:"role,options=admin|member,example=member"`          // 角色：admin / member
	Status    string `json:"status,options=active|disabled,example=active"`     // 状态：active / disabled
	LastLogin int64  `json:"lastLogin,example=1715300000000"`                   // 最近登录时间（Unix 毫秒）
	CreatedAt int64  `json:"createdAt,example=1715200000000"`                   // 创建时间（Unix 毫秒）
}

type ShowWebhook struct {
	ID          int64    `json:"id"`
	UUID        string   `json:"uuid"`
	Name        string   `json:"name"`
	URL         string   `json:"url"`
	Events      []string `json:"events"`
	ChannelType string   `json:"channelType"`
	Status      string   `json:"status"`
	RetryCount  int      `json:"retryCount"`
	TimeoutMs   int      `json:"timeoutMs"`
	LastError   string   `json:"lastError,omitempty"`
	LastTrigger int64    `json:"lastTrigger,omitempty"`
	CreatedAt   int64    `json:"createdAt"`
	UpdatedAt   int64    `json:"updatedAt"`
}

type UpdateKnowledgeBaseRequest struct {
	ID          int64  `path:"id"`                   // 知识库 ID
	Name        string `json:"name,optional"`        // 知识库名称
	Description string `json:"description,optional"` // 知识库描述
}

type UpdateWebhookRequest struct {
	ID         int64    `path:"id"`
	Name       string   `json:"name,optional"`
	URL        string   `json:"url,optional"`
	Secret     string   `json:"secret,optional"`
	Events     []string `json:"events,optional"`
	RetryCount int      `json:"retryCount,optional"`
	TimeoutMs  int      `json:"timeoutMs,optional"`
	Status     string   `json:"status,optional"` // active / disabled
}

type UploadDocumentRequest struct {
	KnowledgeBaseID int64 `path:"kbId"` // 知识库 ID
}

type WebhookDetailResponse struct {
	Code      int32       `json:"code"`
	Msg       string      `json:"msg"`
	Timestamp int64       `json:"timestamp"`
	Data      ShowWebhook `json:"data"`
}

type WebhookInboundRequest struct {
	WebhookID      int64  `path:"webhookId"`                // Webhook 配置 ID
	ExternalUserID string `json:"externalUserId"`           // 外部平台用户标识
	Content        string `json:"content"`                  // 消息内容
	ContentType    string `json:"contentType,default=text"` // 内容类型
	ConversationID int64  `json:"conversationId,optional"`  // 会话 ID（续接已有会话）
}

type WebhookInboundResponse struct {
	Code           int32  `json:"code"`
	Msg            string `json:"msg"`
	Timestamp      int64  `json:"timestamp"`
	ConversationID int64  `json:"conversationId"` // 使用或新建的会话 ID
	MessageID      string `json:"messageId"`      // AI 回复消息 UUID
	Content        string `json:"content"`        // AI 回复内容
}

type WebhookListResponse struct {
	Code      int32         `json:"code"`
	Msg       string        `json:"msg"`
	Timestamp int64         `json:"timestamp"`
	Data      []ShowWebhook `json:"data"`
}
