// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aipivot/internal/shared/po"
)

func newDocumentChunk(db *gorm.DB, opts ...gen.DOOption) documentChunk {
	_documentChunk := documentChunk{}

	_documentChunk.documentChunkDo.UseDB(db, opts...)
	_documentChunk.documentChunkDo.UseModel(&po.DocumentChunk{})

	tableName := _documentChunk.documentChunkDo.TableName()
	_documentChunk.ALL = field.NewAsterisk(tableName)
	_documentChunk.ID = field.NewInt64(tableName, "id")
	_documentChunk.UUID = field.NewString(tableName, "uuid")
	_documentChunk.DocumentID = field.NewInt64(tableName, "document_id")
	_documentChunk.KnowledgeBaseID = field.NewInt64(tableName, "knowledge_base_id")
	_documentChunk.TenantID = field.NewInt64(tableName, "tenant_id")
	_documentChunk.ChunkIndex = field.NewInt(tableName, "chunk_index")
	_documentChunk.Content = field.NewString(tableName, "content")
	_documentChunk.TokenCount = field.NewInt(tableName, "token_count")
	_documentChunk.Metadata = field.NewString(tableName, "metadata")
	_documentChunk.CreatedAt = field.NewTime(tableName, "created_at")

	_documentChunk.fillFieldMap()

	return _documentChunk
}

type documentChunk struct {
	documentChunkDo documentChunkDo

	ALL             field.Asterisk
	ID              field.Int64
	UUID            field.String
	DocumentID      field.Int64
	KnowledgeBaseID field.Int64
	TenantID        field.Int64
	ChunkIndex      field.Int
	Content         field.String
	TokenCount      field.Int
	Metadata        field.String
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (d documentChunk) Table(newTableName string) *documentChunk {
	d.documentChunkDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d documentChunk) As(alias string) *documentChunk {
	d.documentChunkDo.DO = *(d.documentChunkDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *documentChunk) updateTableName(table string) *documentChunk {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.UUID = field.NewString(table, "uuid")
	d.DocumentID = field.NewInt64(table, "document_id")
	d.KnowledgeBaseID = field.NewInt64(table, "knowledge_base_id")
	d.TenantID = field.NewInt64(table, "tenant_id")
	d.ChunkIndex = field.NewInt(table, "chunk_index")
	d.Content = field.NewString(table, "content")
	d.TokenCount = field.NewInt(table, "token_count")
	d.Metadata = field.NewString(table, "metadata")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *documentChunk) WithContext(ctx context.Context) IDocumentChunkDo {
	return d.documentChunkDo.WithContext(ctx)
}

func (d documentChunk) TableName() string { return d.documentChunkDo.TableName() }

func (d documentChunk) Alias() string { return d.documentChunkDo.Alias() }

func (d documentChunk) Columns(cols ...field.Expr) gen.Columns {
	return d.documentChunkDo.Columns(cols...)
}

func (d *documentChunk) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *documentChunk) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["uuid"] = d.UUID
	d.fieldMap["document_id"] = d.DocumentID
	d.fieldMap["knowledge_base_id"] = d.KnowledgeBaseID
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["chunk_index"] = d.ChunkIndex
	d.fieldMap["content"] = d.Content
	d.fieldMap["token_count"] = d.TokenCount
	d.fieldMap["metadata"] = d.Metadata
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d documentChunk) clone(db *gorm.DB) documentChunk {
	d.documentChunkDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d documentChunk) replaceDB(db *gorm.DB) documentChunk {
	d.documentChunkDo.ReplaceDB(db)
	return d
}

type documentChunkDo struct{ gen.DO }

type IDocumentChunkDo interface {
	gen.SubQuery
	Debug() IDocumentChunkDo
	WithContext(ctx context.Context) IDocumentChunkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDocumentChunkDo
	WriteDB() IDocumentChunkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDocumentChunkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDocumentChunkDo
	Not(conds ...gen.Condition) IDocumentChunkDo
	Or(conds ...gen.Condition) IDocumentChunkDo
	Select(conds ...field.Expr) IDocumentChunkDo
	Where(conds ...gen.Condition) IDocumentChunkDo
	Order(conds ...field.Expr) IDocumentChunkDo
	Distinct(cols ...field.Expr) IDocumentChunkDo
	Omit(cols ...field.Expr) IDocumentChunkDo
	Join(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo
	Group(cols ...field.Expr) IDocumentChunkDo
	Having(conds ...gen.Condition) IDocumentChunkDo
	Limit(limit int) IDocumentChunkDo
	Offset(offset int) IDocumentChunkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentChunkDo
	Unscoped() IDocumentChunkDo
	Create(values ...*po.DocumentChunk) error
	CreateInBatches(values []*po.DocumentChunk, batchSize int) error
	Save(values ...*po.DocumentChunk) error
	First() (*po.DocumentChunk, error)
	Take() (*po.DocumentChunk, error)
	Last() (*po.DocumentChunk, error)
	Find() ([]*po.DocumentChunk, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.DocumentChunk, err error)
	FindInBatches(result *[]*po.DocumentChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*po.DocumentChunk) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDocumentChunkDo
	Assign(attrs ...field.AssignExpr) IDocumentChunkDo
	Joins(fields ...field.RelationField) IDocumentChunkDo
	Preload(fields ...field.RelationField) IDocumentChunkDo
	FirstOrInit() (*po.DocumentChunk, error)
	FirstOrCreate() (*po.DocumentChunk, error)
	FindByPage(offset int, limit int) (result []*po.DocumentChunk, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDocumentChunkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d documentChunkDo) Debug() IDocumentChunkDo {
	return d.withDO(d.DO.Debug())
}

func (d documentChunkDo) WithContext(ctx context.Context) IDocumentChunkDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d documentChunkDo) ReadDB() IDocumentChunkDo {
	return d.Clauses(dbresolver.Read)
}

func (d documentChunkDo) WriteDB() IDocumentChunkDo {
	return d.Clauses(dbresolver.Write)
}

func (d documentChunkDo) Session(config *gorm.Session) IDocumentChunkDo {
	return d.withDO(d.DO.Session(config))
}

func (d documentChunkDo) Clauses(conds ...clause.Expression) IDocumentChunkDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d documentChunkDo) Returning(value interface{}, columns ...string) IDocumentChunkDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d documentChunkDo) Not(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d documentChunkDo) Or(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d documentChunkDo) Select(conds ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d documentChunkDo) Where(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d documentChunkDo) Order(conds ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d documentChunkDo) Distinct(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d documentChunkDo) Omit(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d documentChunkDo) Join(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d documentChunkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d documentChunkDo) RightJoin(table schema.Tabler, on ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d documentChunkDo) Group(cols ...field.Expr) IDocumentChunkDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d documentChunkDo) Having(conds ...gen.Condition) IDocumentChunkDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d documentChunkDo) Limit(limit int) IDocumentChunkDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d documentChunkDo) Offset(offset int) IDocumentChunkDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d documentChunkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDocumentChunkDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d documentChunkDo) Unscoped() IDocumentChunkDo {
	return d.withDO(d.DO.Unscoped())
}

func (d documentChunkDo) Create(values ...*po.DocumentChunk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d documentChunkDo) CreateInBatches(values []*po.DocumentChunk, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d documentChunkDo) Save(values ...*po.DocumentChunk) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d documentChunkDo) First() (*po.DocumentChunk, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.DocumentChunk), nil
	}
}

func (d documentChunkDo) Take() (*po.DocumentChunk, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.DocumentChunk), nil
	}
}

func (d documentChunkDo) Last() (*po.DocumentChunk, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.DocumentChunk), nil
	}
}

func (d documentChunkDo) Find() ([]*po.DocumentChunk, error) {
	result, err := d.DO.Find()
	return result.([]*po.DocumentChunk), err
}

func (d documentChunkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.DocumentChunk, err error) {
	buf := make([]*po.DocumentChunk, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d documentChunkDo) FindInBatches(result *[]*po.DocumentChunk, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d documentChunkDo) Attrs(attrs ...field.AssignExpr) IDocumentChunkDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d documentChunkDo) Assign(attrs ...field.AssignExpr) IDocumentChunkDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d documentChunkDo) Joins(fields ...field.RelationField) IDocumentChunkDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d documentChunkDo) Preload(fields ...field.RelationField) IDocumentChunkDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d documentChunkDo) FirstOrInit() (*po.DocumentChunk, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.DocumentChunk), nil
	}
}

func (d documentChunkDo) FirstOrCreate() (*po.DocumentChunk, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.DocumentChunk), nil
	}
}

func (d documentChunkDo) FindByPage(offset int, limit int) (result []*po.DocumentChunk, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d documentChunkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d documentChunkDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d documentChunkDo) Delete(models ...*po.DocumentChunk) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *documentChunkDo) withDO(do gen.Dao) *documentChunkDo {
	d.DO = *do.(*gen.DO)
	return d
}
