// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aipivot/internal/shared/po"
)

func newFlow(db *gorm.DB, opts ...gen.DOOption) flow {
	_flow := flow{}

	_flow.flowDo.UseDB(db, opts...)
	_flow.flowDo.UseModel(&po.Flow{})

	tableName := _flow.flowDo.TableName()
	_flow.ALL = field.NewAsterisk(tableName)
	_flow.ID = field.NewInt64(tableName, "id")
	_flow.UUID = field.NewString(tableName, "uuid")
	_flow.TenantID = field.NewInt64(tableName, "tenant_id")
	_flow.Name = field.NewString(tableName, "name")
	_flow.Description = field.NewString(tableName, "description")
	_flow.Definition = field.NewField(tableName, "definition")
	_flow.Status = field.NewString(tableName, "status")
	_flow.Version = field.NewInt(tableName, "version")
	_flow.CreatedAt = field.NewTime(tableName, "created_at")
	_flow.UpdatedAt = field.NewTime(tableName, "updated_at")

	_flow.fillFieldMap()

	return _flow
}

type flow struct {
	flowDo flowDo

	ALL         field.Asterisk
	ID          field.Int64
	UUID        field.String
	TenantID    field.Int64
	Name        field.String
	Description field.String
	Definition  field.Field
	Status      field.String
	Version     field.Int
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (f flow) Table(newTableName string) *flow {
	f.flowDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flow) As(alias string) *flow {
	f.flowDo.DO = *(f.flowDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flow) updateTableName(table string) *flow {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UUID = field.NewString(table, "uuid")
	f.TenantID = field.NewInt64(table, "tenant_id")
	f.Name = field.NewString(table, "name")
	f.Description = field.NewString(table, "description")
	f.Definition = field.NewField(table, "definition")
	f.Status = field.NewString(table, "status")
	f.Version = field.NewInt(table, "version")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *flow) WithContext(ctx context.Context) IFlowDo { return f.flowDo.WithContext(ctx) }

func (f flow) TableName() string { return f.flowDo.TableName() }

func (f flow) Alias() string { return f.flowDo.Alias() }

func (f flow) Columns(cols ...field.Expr) gen.Columns { return f.flowDo.Columns(cols...) }

func (f *flow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flow) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 10)
	f.fieldMap["id"] = f.ID
	f.fieldMap["uuid"] = f.UUID
	f.fieldMap["tenant_id"] = f.TenantID
	f.fieldMap["name"] = f.Name
	f.fieldMap["description"] = f.Description
	f.fieldMap["definition"] = f.Definition
	f.fieldMap["status"] = f.Status
	f.fieldMap["version"] = f.Version
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f flow) clone(db *gorm.DB) flow {
	f.flowDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flow) replaceDB(db *gorm.DB) flow {
	f.flowDo.ReplaceDB(db)
	return f
}

type flowDo struct{ gen.DO }

type IFlowDo interface {
	gen.SubQuery
	Debug() IFlowDo
	WithContext(ctx context.Context) IFlowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFlowDo
	WriteDB() IFlowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFlowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFlowDo
	Not(conds ...gen.Condition) IFlowDo
	Or(conds ...gen.Condition) IFlowDo
	Select(conds ...field.Expr) IFlowDo
	Where(conds ...gen.Condition) IFlowDo
	Order(conds ...field.Expr) IFlowDo
	Distinct(cols ...field.Expr) IFlowDo
	Omit(cols ...field.Expr) IFlowDo
	Join(table schema.Tabler, on ...field.Expr) IFlowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFlowDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFlowDo
	Group(cols ...field.Expr) IFlowDo
	Having(conds ...gen.Condition) IFlowDo
	Limit(limit int) IFlowDo
	Offset(offset int) IFlowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowDo
	Unscoped() IFlowDo
	Create(values ...*po.Flow) error
	CreateInBatches(values []*po.Flow, batchSize int) error
	Save(values ...*po.Flow) error
	First() (*po.Flow, error)
	Take() (*po.Flow, error)
	Last() (*po.Flow, error)
	Find() ([]*po.Flow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.Flow, err error)
	FindInBatches(result *[]*po.Flow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*po.Flow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFlowDo
	Assign(attrs ...field.AssignExpr) IFlowDo
	Joins(fields ...field.RelationField) IFlowDo
	Preload(fields ...field.RelationField) IFlowDo
	FirstOrInit() (*po.Flow, error)
	FirstOrCreate() (*po.Flow, error)
	FindByPage(offset int, limit int) (result []*po.Flow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFlowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f flowDo) Debug() IFlowDo {
	return f.withDO(f.DO.Debug())
}

func (f flowDo) WithContext(ctx context.Context) IFlowDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flowDo) ReadDB() IFlowDo {
	return f.Clauses(dbresolver.Read)
}

func (f flowDo) WriteDB() IFlowDo {
	return f.Clauses(dbresolver.Write)
}

func (f flowDo) Session(config *gorm.Session) IFlowDo {
	return f.withDO(f.DO.Session(config))
}

func (f flowDo) Clauses(conds ...clause.Expression) IFlowDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flowDo) Returning(value interface{}, columns ...string) IFlowDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flowDo) Not(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flowDo) Or(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flowDo) Select(conds ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flowDo) Where(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flowDo) Order(conds ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flowDo) Distinct(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flowDo) Omit(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flowDo) Join(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flowDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flowDo) RightJoin(table schema.Tabler, on ...field.Expr) IFlowDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flowDo) Group(cols ...field.Expr) IFlowDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flowDo) Having(conds ...gen.Condition) IFlowDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flowDo) Limit(limit int) IFlowDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flowDo) Offset(offset int) IFlowDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flowDo) Unscoped() IFlowDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flowDo) Create(values ...*po.Flow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flowDo) CreateInBatches(values []*po.Flow, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flowDo) Save(values ...*po.Flow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flowDo) First() (*po.Flow, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.Flow), nil
	}
}

func (f flowDo) Take() (*po.Flow, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.Flow), nil
	}
}

func (f flowDo) Last() (*po.Flow, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.Flow), nil
	}
}

func (f flowDo) Find() ([]*po.Flow, error) {
	result, err := f.DO.Find()
	return result.([]*po.Flow), err
}

func (f flowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.Flow, err error) {
	buf := make([]*po.Flow, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flowDo) FindInBatches(result *[]*po.Flow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flowDo) Attrs(attrs ...field.AssignExpr) IFlowDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flowDo) Assign(attrs ...field.AssignExpr) IFlowDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flowDo) Joins(fields ...field.RelationField) IFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flowDo) Preload(fields ...field.RelationField) IFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flowDo) FirstOrInit() (*po.Flow, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.Flow), nil
	}
}

func (f flowDo) FirstOrCreate() (*po.Flow, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.Flow), nil
	}
}

func (f flowDo) FindByPage(offset int, limit int) (result []*po.Flow, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flowDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flowDo) Delete(models ...*po.Flow) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flowDo) withDO(do gen.Dao) *flowDo {
	f.DO = *do.(*gen.DO)
	return f
}
