// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aipivot/internal/shared/po"
)

func newFlowRun(db *gorm.DB, opts ...gen.DOOption) flowRun {
	_flowRun := flowRun{}

	_flowRun.flowRunDo.UseDB(db, opts...)
	_flowRun.flowRunDo.UseModel(&po.FlowRun{})

	tableName := _flowRun.flowRunDo.TableName()
	_flowRun.ALL = field.NewAsterisk(tableName)
	_flowRun.ID = field.NewInt64(tableName, "id")
	_flowRun.UUID = field.NewString(tableName, "uuid")
	_flowRun.TenantID = field.NewInt64(tableName, "tenant_id")
	_flowRun.FlowID = field.NewInt64(tableName, "flow_id")
	_flowRun.FlowVersion = field.NewInt(tableName, "flow_version")
	_flowRun.Status = field.NewString(tableName, "status")
	_flowRun.TriggerType = field.NewString(tableName, "trigger_type")
	_flowRun.Input = field.NewField(tableName, "input")
	_flowRun.Output = field.NewString(tableName, "output")
	_flowRun.NodeResults = field.NewString(tableName, "node_results")
	_flowRun.Error = field.NewString(tableName, "error")
	_flowRun.TotalMs = field.NewInt(tableName, "total_ms")
	_flowRun.TokenCount = field.NewInt(tableName, "token_count")
	_flowRun.CreatedAt = field.NewTime(tableName, "created_at")
	_flowRun.UpdatedAt = field.NewTime(tableName, "updated_at")

	_flowRun.fillFieldMap()

	return _flowRun
}

type flowRun struct {
	flowRunDo flowRunDo

	ALL         field.Asterisk
	ID          field.Int64
	UUID        field.String
	TenantID    field.Int64
	FlowID      field.Int64
	FlowVersion field.Int
	Status      field.String
	TriggerType field.String
	Input       field.Field
	Output      field.String
	NodeResults field.String
	Error       field.String
	TotalMs     field.Int
	TokenCount  field.Int
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (f flowRun) Table(newTableName string) *flowRun {
	f.flowRunDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flowRun) As(alias string) *flowRun {
	f.flowRunDo.DO = *(f.flowRunDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flowRun) updateTableName(table string) *flowRun {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.UUID = field.NewString(table, "uuid")
	f.TenantID = field.NewInt64(table, "tenant_id")
	f.FlowID = field.NewInt64(table, "flow_id")
	f.FlowVersion = field.NewInt(table, "flow_version")
	f.Status = field.NewString(table, "status")
	f.TriggerType = field.NewString(table, "trigger_type")
	f.Input = field.NewField(table, "input")
	f.Output = field.NewString(table, "output")
	f.NodeResults = field.NewString(table, "node_results")
	f.Error = field.NewString(table, "error")
	f.TotalMs = field.NewInt(table, "total_ms")
	f.TokenCount = field.NewInt(table, "token_count")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *flowRun) WithContext(ctx context.Context) IFlowRunDo { return f.flowRunDo.WithContext(ctx) }

func (f flowRun) TableName() string { return f.flowRunDo.TableName() }

func (f flowRun) Alias() string { return f.flowRunDo.Alias() }

func (f flowRun) Columns(cols ...field.Expr) gen.Columns { return f.flowRunDo.Columns(cols...) }

func (f *flowRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flowRun) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 15)
	f.fieldMap["id"] = f.ID
	f.fieldMap["uuid"] = f.UUID
	f.fieldMap["tenant_id"] = f.TenantID
	f.fieldMap["flow_id"] = f.FlowID
	f.fieldMap["flow_version"] = f.FlowVersion
	f.fieldMap["status"] = f.Status
	f.fieldMap["trigger_type"] = f.TriggerType
	f.fieldMap["input"] = f.Input
	f.fieldMap["output"] = f.Output
	f.fieldMap["node_results"] = f.NodeResults
	f.fieldMap["error"] = f.Error
	f.fieldMap["total_ms"] = f.TotalMs
	f.fieldMap["token_count"] = f.TokenCount
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f flowRun) clone(db *gorm.DB) flowRun {
	f.flowRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flowRun) replaceDB(db *gorm.DB) flowRun {
	f.flowRunDo.ReplaceDB(db)
	return f
}

type flowRunDo struct{ gen.DO }

type IFlowRunDo interface {
	gen.SubQuery
	Debug() IFlowRunDo
	WithContext(ctx context.Context) IFlowRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFlowRunDo
	WriteDB() IFlowRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFlowRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFlowRunDo
	Not(conds ...gen.Condition) IFlowRunDo
	Or(conds ...gen.Condition) IFlowRunDo
	Select(conds ...field.Expr) IFlowRunDo
	Where(conds ...gen.Condition) IFlowRunDo
	Order(conds ...field.Expr) IFlowRunDo
	Distinct(cols ...field.Expr) IFlowRunDo
	Omit(cols ...field.Expr) IFlowRunDo
	Join(table schema.Tabler, on ...field.Expr) IFlowRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFlowRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFlowRunDo
	Group(cols ...field.Expr) IFlowRunDo
	Having(conds ...gen.Condition) IFlowRunDo
	Limit(limit int) IFlowRunDo
	Offset(offset int) IFlowRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowRunDo
	Unscoped() IFlowRunDo
	Create(values ...*po.FlowRun) error
	CreateInBatches(values []*po.FlowRun, batchSize int) error
	Save(values ...*po.FlowRun) error
	First() (*po.FlowRun, error)
	Take() (*po.FlowRun, error)
	Last() (*po.FlowRun, error)
	Find() ([]*po.FlowRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.FlowRun, err error)
	FindInBatches(result *[]*po.FlowRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*po.FlowRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFlowRunDo
	Assign(attrs ...field.AssignExpr) IFlowRunDo
	Joins(fields ...field.RelationField) IFlowRunDo
	Preload(fields ...field.RelationField) IFlowRunDo
	FirstOrInit() (*po.FlowRun, error)
	FirstOrCreate() (*po.FlowRun, error)
	FindByPage(offset int, limit int) (result []*po.FlowRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFlowRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f flowRunDo) Debug() IFlowRunDo {
	return f.withDO(f.DO.Debug())
}

func (f flowRunDo) WithContext(ctx context.Context) IFlowRunDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flowRunDo) ReadDB() IFlowRunDo {
	return f.Clauses(dbresolver.Read)
}

func (f flowRunDo) WriteDB() IFlowRunDo {
	return f.Clauses(dbresolver.Write)
}

func (f flowRunDo) Session(config *gorm.Session) IFlowRunDo {
	return f.withDO(f.DO.Session(config))
}

func (f flowRunDo) Clauses(conds ...clause.Expression) IFlowRunDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flowRunDo) Returning(value interface{}, columns ...string) IFlowRunDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flowRunDo) Not(conds ...gen.Condition) IFlowRunDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flowRunDo) Or(conds ...gen.Condition) IFlowRunDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flowRunDo) Select(conds ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flowRunDo) Where(conds ...gen.Condition) IFlowRunDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flowRunDo) Order(conds ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flowRunDo) Distinct(cols ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flowRunDo) Omit(cols ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flowRunDo) Join(table schema.Tabler, on ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flowRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flowRunDo) RightJoin(table schema.Tabler, on ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flowRunDo) Group(cols ...field.Expr) IFlowRunDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flowRunDo) Having(conds ...gen.Condition) IFlowRunDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flowRunDo) Limit(limit int) IFlowRunDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flowRunDo) Offset(offset int) IFlowRunDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flowRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowRunDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flowRunDo) Unscoped() IFlowRunDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flowRunDo) Create(values ...*po.FlowRun) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flowRunDo) CreateInBatches(values []*po.FlowRun, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flowRunDo) Save(values ...*po.FlowRun) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flowRunDo) First() (*po.FlowRun, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.FlowRun), nil
	}
}

func (f flowRunDo) Take() (*po.FlowRun, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.FlowRun), nil
	}
}

func (f flowRunDo) Last() (*po.FlowRun, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.FlowRun), nil
	}
}

func (f flowRunDo) Find() ([]*po.FlowRun, error) {
	result, err := f.DO.Find()
	return result.([]*po.FlowRun), err
}

func (f flowRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.FlowRun, err error) {
	buf := make([]*po.FlowRun, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flowRunDo) FindInBatches(result *[]*po.FlowRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flowRunDo) Attrs(attrs ...field.AssignExpr) IFlowRunDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flowRunDo) Assign(attrs ...field.AssignExpr) IFlowRunDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flowRunDo) Joins(fields ...field.RelationField) IFlowRunDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flowRunDo) Preload(fields ...field.RelationField) IFlowRunDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flowRunDo) FirstOrInit() (*po.FlowRun, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.FlowRun), nil
	}
}

func (f flowRunDo) FirstOrCreate() (*po.FlowRun, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.FlowRun), nil
	}
}

func (f flowRunDo) FindByPage(offset int, limit int) (result []*po.FlowRun, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flowRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flowRunDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flowRunDo) Delete(models ...*po.FlowRun) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flowRunDo) withDO(do gen.Dao) *flowRunDo {
	f.DO = *do.(*gen.DO)
	return f
}
