// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	ApiKey        *apiKey
	Conversation  *conversation
	Document      *document
	DocumentChunk *documentChunk
	Flow          *flow
	KnowledgeBase *knowledgeBase
	Message       *message
	Skill         *skill
	Tenant        *tenant
	User          *user
	Webhook       *webhook
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ApiKey = &Q.ApiKey
	Conversation = &Q.Conversation
	Document = &Q.Document
	DocumentChunk = &Q.DocumentChunk
	Flow = &Q.Flow
	KnowledgeBase = &Q.KnowledgeBase
	Message = &Q.Message
	Skill = &Q.Skill
	Tenant = &Q.Tenant
	User = &Q.User
	Webhook = &Q.Webhook
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		ApiKey:        newApiKey(db, opts...),
		Conversation:  newConversation(db, opts...),
		Document:      newDocument(db, opts...),
		DocumentChunk: newDocumentChunk(db, opts...),
		Flow:          newFlow(db, opts...),
		KnowledgeBase: newKnowledgeBase(db, opts...),
		Message:       newMessage(db, opts...),
		Skill:         newSkill(db, opts...),
		Tenant:        newTenant(db, opts...),
		User:          newUser(db, opts...),
		Webhook:       newWebhook(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ApiKey        apiKey
	Conversation  conversation
	Document      document
	DocumentChunk documentChunk
	Flow          flow
	KnowledgeBase knowledgeBase
	Message       message
	Skill         skill
	Tenant        tenant
	User          user
	Webhook       webhook
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		ApiKey:        q.ApiKey.clone(db),
		Conversation:  q.Conversation.clone(db),
		Document:      q.Document.clone(db),
		DocumentChunk: q.DocumentChunk.clone(db),
		Flow:          q.Flow.clone(db),
		KnowledgeBase: q.KnowledgeBase.clone(db),
		Message:       q.Message.clone(db),
		Skill:         q.Skill.clone(db),
		Tenant:        q.Tenant.clone(db),
		User:          q.User.clone(db),
		Webhook:       q.Webhook.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		ApiKey:        q.ApiKey.replaceDB(db),
		Conversation:  q.Conversation.replaceDB(db),
		Document:      q.Document.replaceDB(db),
		DocumentChunk: q.DocumentChunk.replaceDB(db),
		Flow:          q.Flow.replaceDB(db),
		KnowledgeBase: q.KnowledgeBase.replaceDB(db),
		Message:       q.Message.replaceDB(db),
		Skill:         q.Skill.replaceDB(db),
		Tenant:        q.Tenant.replaceDB(db),
		User:          q.User.replaceDB(db),
		Webhook:       q.Webhook.replaceDB(db),
	}
}

type queryCtx struct {
	ApiKey        IApiKeyDo
	Conversation  IConversationDo
	Document      IDocumentDo
	DocumentChunk IDocumentChunkDo
	Flow          IFlowDo
	KnowledgeBase IKnowledgeBaseDo
	Message       IMessageDo
	Skill         ISkillDo
	Tenant        ITenantDo
	User          IUserDo
	Webhook       IWebhookDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ApiKey:        q.ApiKey.WithContext(ctx),
		Conversation:  q.Conversation.WithContext(ctx),
		Document:      q.Document.WithContext(ctx),
		DocumentChunk: q.DocumentChunk.WithContext(ctx),
		Flow:          q.Flow.WithContext(ctx),
		KnowledgeBase: q.KnowledgeBase.WithContext(ctx),
		Message:       q.Message.WithContext(ctx),
		Skill:         q.Skill.WithContext(ctx),
		Tenant:        q.Tenant.WithContext(ctx),
		User:          q.User.WithContext(ctx),
		Webhook:       q.Webhook.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
