// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "aipivot/internal/handler/admin"
	analytics "aipivot/internal/handler/analytics"
	apikey "aipivot/internal/handler/apikey"
	auth "aipivot/internal/handler/auth"
	chat "aipivot/internal/handler/chat"
	infra "aipivot/internal/handler/infra"
	knowledge "aipivot/internal/handler/knowledge"
	models "aipivot/internal/handler/models"
	open "aipivot/internal/handler/open"
	skills "aipivot/internal/handler/skills"
	webhook "aipivot/internal/handler/webhook"
	"aipivot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					// 获取当前租户信息
					Method:  http.MethodGet,
					Path:    "/tenant",
					Handler: admin.GetTenantHandler(serverCtx),
				},
				{
					// 更新当前租户设置
					Method:  http.MethodPut,
					Path:    "/tenant",
					Handler: admin.UpdateTenantHandler(serverCtx),
				},
				{
					// 获取租户用户列表
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: admin.ListUsersHandler(serverCtx),
				},
				{
					// 创建租户用户
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: admin.CreateUserHandler(serverCtx),
				},
				{
					// 更新租户用户
					Method:  http.MethodPut,
					Path:    "/users/:id",
					Handler: admin.UpdateUserHandler(serverCtx),
				},
				{
					// 删除租户用户
					Method:  http.MethodDelete,
					Path:    "/users/:id",
					Handler: admin.DeleteUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取日粒度对话统计趋势（最近 N 天）
					Method:  http.MethodGet,
					Path:    "/analytics/daily",
					Handler: analytics.AnalyticsDailyHandler(serverCtx),
				},
				{
					// 导出 SLA 报表 CSV
					Method:  http.MethodGet,
					Path:    "/analytics/export",
					Handler: analytics.ExportReportHandler(serverCtx),
				},
				{
					// 获取对话分析概览（会话数/消息数/Token/费用/解决率/渠道分布）
					Method:  http.MethodGet,
					Path:    "/analytics/overview",
					Handler: analytics.AnalyticsOverviewHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建 API Key
					Method:  http.MethodPost,
					Path:    "/api-keys",
					Handler: apikey.CreateApiKeyHandler(serverCtx),
				},
				{
					// 获取 API Key 列表
					Method:  http.MethodGet,
					Path:    "/api-keys",
					Handler: apikey.ListApiKeyHandler(serverCtx),
				},
				{
					// 吊销 API Key
					Method:  http.MethodPut,
					Path:    "/api-keys/:id/revoke",
					Handler: apikey.RevokeApiKeyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录 - 使用邮箱和密码登录，返回 JWT 令牌及用户信息
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 用户注册 - 使用邮箱注册新账户（MVP 阶段自动绑定默认租户）
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建会话
					Method:  http.MethodPost,
					Path:    "/conversations",
					Handler: chat.CreateConversationHandler(serverCtx),
				},
				{
					// 获取会话列表
					Method:  http.MethodGet,
					Path:    "/conversations",
					Handler: chat.ListConversationHandler(serverCtx),
				},
				{
					// 发送消息（同步模式，MVP 阶段）
					Method:  http.MethodPost,
					Path:    "/conversations/:convId/messages",
					Handler: chat.SendMessageHandler(serverCtx),
				},
				{
					// 获取消息历史
					Method:  http.MethodGet,
					Path:    "/conversations/:convId/messages",
					Handler: chat.ListMessageHandler(serverCtx),
				},
				{
					// 获取会话详情
					Method:  http.MethodGet,
					Path:    "/conversations/:id",
					Handler: chat.GetConversationHandler(serverCtx),
				},
				{
					// 关闭会话
					Method:  http.MethodPut,
					Path:    "/conversations/:id/close",
					Handler: chat.CloseConversationHandler(serverCtx),
				},
				{
					// 转接人工客服
					Method:  http.MethodPut,
					Path:    "/conversations/:id/escalate",
					Handler: chat.EscalateConversationHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查 - 返回服务存活状态，供 K8s livenessProbe 使用
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: infra.HealthHandler(serverCtx),
			},
			{
				// 指标采集 - 返回 Prometheus 格式的监控指标
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: infra.MetricsHandler(serverCtx),
			},
			{
				// 就绪检查 - 返回服务及依赖组件就绪状态，供 K8s readinessProbe 使用
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: infra.ReadyHandler(serverCtx),
			},
			{
				// 连通性测试 - 返回 pong 及请求追踪信息
				Method:  http.MethodGet,
				Path:    "/v1/ping",
				Handler: infra.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建知识库
					Method:  http.MethodPost,
					Path:    "/knowledge-bases",
					Handler: knowledge.CreateKnowledgeBaseHandler(serverCtx),
				},
				{
					// 获取知识库列表
					Method:  http.MethodGet,
					Path:    "/knowledge-bases",
					Handler: knowledge.ListKnowledgeBaseHandler(serverCtx),
				},
				{
					// 获取知识库详情
					Method:  http.MethodGet,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.GetKnowledgeBaseHandler(serverCtx),
				},
				{
					// 更新知识库
					Method:  http.MethodPut,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.UpdateKnowledgeBaseHandler(serverCtx),
				},
				{
					// 删除知识库
					Method:  http.MethodDelete,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.DeleteKnowledgeBaseHandler(serverCtx),
				},
				{
					// 上传文档到知识库
					Method:  http.MethodPost,
					Path:    "/knowledge-bases/:kbId/documents",
					Handler: knowledge.UploadDocumentHandler(serverCtx),
				},
				{
					// 获取知识库文档列表
					Method:  http.MethodGet,
					Path:    "/knowledge-bases/:kbId/documents",
					Handler: knowledge.ListDocumentHandler(serverCtx),
				},
				{
					// 删除文档
					Method:  http.MethodDelete,
					Path:    "/knowledge-bases/:kbId/documents/:id",
					Handler: knowledge.DeleteDocumentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 获取可用模型列表
					Method:  http.MethodGet,
					Path:    "/models",
					Handler: models.ListModelsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Chat Completion（同步）— OpenAI 兼容格式，通过 API Key 认证
				Method:  http.MethodPost,
				Path:    "/chat/completions",
				Handler: open.ChatCompletionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/open"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Webhook 入站消息 — 接收外部平台推送的用户消息并返回 AI 回复
				Method:  http.MethodPost,
				Path:    "/webhook/:webhookId/inbound",
				Handler: open.WebhookInboundHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/open"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					// 创建自定义工具
					Method:  http.MethodPost,
					Path:    "/skills",
					Handler: skills.CreateSkillHandler(serverCtx),
				},
				{
					// 获取工具列表
					Method:  http.MethodGet,
					Path:    "/skills",
					Handler: skills.ListSkillsHandler(serverCtx),
				},
				{
					// 获取工具详情
					Method:  http.MethodGet,
					Path:    "/skills/:id",
					Handler: skills.GetSkillHandler(serverCtx),
				},
				{
					// 更新工具
					Method:  http.MethodPut,
					Path:    "/skills/:id",
					Handler: skills.UpdateSkillHandler(serverCtx),
				},
				{
					// 删除工具
					Method:  http.MethodDelete,
					Path:    "/skills/:id",
					Handler: skills.DeleteSkillHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建 Webhook
					Method:  http.MethodPost,
					Path:    "/webhooks",
					Handler: webhook.CreateWebhookHandler(serverCtx),
				},
				{
					// 获取 Webhook 列表
					Method:  http.MethodGet,
					Path:    "/webhooks",
					Handler: webhook.ListWebhookHandler(serverCtx),
				},
				{
					// 获取 Webhook 详情
					Method:  http.MethodGet,
					Path:    "/webhooks/:id",
					Handler: webhook.GetWebhookHandler(serverCtx),
				},
				{
					// 更新 Webhook
					Method:  http.MethodPut,
					Path:    "/webhooks/:id",
					Handler: webhook.UpdateWebhookHandler(serverCtx),
				},
				{
					// 删除 Webhook
					Method:  http.MethodDelete,
					Path:    "/webhooks/:id",
					Handler: webhook.DeleteWebhookHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
