// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "aipivot/internal/handler/auth"
	chat "aipivot/internal/handler/chat"
	infra "aipivot/internal/handler/infra"
	knowledge "aipivot/internal/handler/knowledge"
	"aipivot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录 - 使用邮箱和密码登录，返回 JWT 令牌及用户信息
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 用户注册 - 使用邮箱注册新账户（MVP 阶段自动绑定默认租户）
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建会话
					Method:  http.MethodPost,
					Path:    "/conversations",
					Handler: chat.CreateConversationHandler(serverCtx),
				},
				{
					// 获取会话列表
					Method:  http.MethodGet,
					Path:    "/conversations",
					Handler: chat.ListConversationHandler(serverCtx),
				},
				{
					// 发送消息（同步模式，MVP 阶段）
					Method:  http.MethodPost,
					Path:    "/conversations/:convId/messages",
					Handler: chat.SendMessageHandler(serverCtx),
				},
				{
					// 获取消息历史
					Method:  http.MethodGet,
					Path:    "/conversations/:convId/messages",
					Handler: chat.ListMessageHandler(serverCtx),
				},
				{
					// 获取会话详情
					Method:  http.MethodGet,
					Path:    "/conversations/:id",
					Handler: chat.GetConversationHandler(serverCtx),
				},
				{
					// 关闭会话
					Method:  http.MethodPut,
					Path:    "/conversations/:id/close",
					Handler: chat.CloseConversationHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查 - 返回服务存活状态，供 K8s livenessProbe 使用
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: infra.HealthHandler(serverCtx),
			},
			{
				// 指标采集 - 返回 Prometheus 格式的监控指标
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: infra.MetricsHandler(serverCtx),
			},
			{
				// 就绪检查 - 返回服务及依赖组件就绪状态，供 K8s readinessProbe 使用
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: infra.ReadyHandler(serverCtx),
			},
			{
				// 连通性测试 - 返回 pong 及请求追踪信息
				Method:  http.MethodGet,
				Path:    "/v1/ping",
				Handler: infra.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					// 创建知识库
					Method:  http.MethodPost,
					Path:    "/knowledge-bases",
					Handler: knowledge.CreateKnowledgeBaseHandler(serverCtx),
				},
				{
					// 获取知识库列表
					Method:  http.MethodGet,
					Path:    "/knowledge-bases",
					Handler: knowledge.ListKnowledgeBaseHandler(serverCtx),
				},
				{
					// 获取知识库详情
					Method:  http.MethodGet,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.GetKnowledgeBaseHandler(serverCtx),
				},
				{
					// 更新知识库
					Method:  http.MethodPut,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.UpdateKnowledgeBaseHandler(serverCtx),
				},
				{
					// 删除知识库
					Method:  http.MethodDelete,
					Path:    "/knowledge-bases/:id",
					Handler: knowledge.DeleteKnowledgeBaseHandler(serverCtx),
				},
				{
					// 上传文档到知识库
					Method:  http.MethodPost,
					Path:    "/knowledge-bases/:kbId/documents",
					Handler: knowledge.UploadDocumentHandler(serverCtx),
				},
				{
					// 获取知识库文档列表
					Method:  http.MethodGet,
					Path:    "/knowledge-bases/:kbId/documents",
					Handler: knowledge.ListDocumentHandler(serverCtx),
				},
				{
					// 删除文档
					Method:  http.MethodDelete,
					Path:    "/knowledge-bases/:kbId/documents/:id",
					Handler: knowledge.DeleteDocumentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
